// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNZi4V4r_xsXs9xUsqxv7A6RO6PbAyZI',
    appId: '1:65147047369:web:d8f9e2c3b9faa316a9ec18',
    messagingSenderId: '65147047369',
    projectId: 'tshirtsfreemarket',
    authDomain: 'tshirtsfreemarket.firebaseapp.com',
    databaseURL: 'https://tshirtsfreemarket-default-rtdb.firebaseio.com',
    storageBucket: 'tshirtsfreemarket.appspot.com',
    measurementId: 'G-9BPZ4C732Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQOa-mfSiUUFDcRNxXCzfqTjbcTiYkW9c',
    appId: '1:65147047369:android:76fe842f8a728a3ca9ec18',
    messagingSenderId: '65147047369',
    projectId: 'tshirtsfreemarket',
    databaseURL: 'https://tshirtsfreemarket-default-rtdb.firebaseio.com',
    storageBucket: 'tshirtsfreemarket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBagClt7JmsBk5E9ucTEHesmKEefuELCBE',
    appId: '1:65147047369:ios:ceb9acc869aa0c1aa9ec18',
    messagingSenderId: '65147047369',
    projectId: 'tshirtsfreemarket',
    databaseURL: 'https://tshirtsfreemarket-default-rtdb.firebaseio.com',
    storageBucket: 'tshirtsfreemarket.appspot.com',
    androidClientId: '65147047369-3m8kmmfpv46t0lqblrgt0cgk2ul24lct.apps.googleusercontent.com',
    iosClientId: '65147047369-j65g78n50pr0q3rppti67de58jotbqtm.apps.googleusercontent.com',
    iosBundleId: 'com.imakita3gyo.tfreemarket.tfreemarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBagClt7JmsBk5E9ucTEHesmKEefuELCBE',
    appId: '1:65147047369:ios:ceb9acc869aa0c1aa9ec18',
    messagingSenderId: '65147047369',
    projectId: 'tshirtsfreemarket',
    databaseURL: 'https://tshirtsfreemarket-default-rtdb.firebaseio.com',
    storageBucket: 'tshirtsfreemarket.appspot.com',
    androidClientId: '65147047369-3m8kmmfpv46t0lqblrgt0cgk2ul24lct.apps.googleusercontent.com',
    iosClientId: '65147047369-j65g78n50pr0q3rppti67de58jotbqtm.apps.googleusercontent.com',
    iosBundleId: 'com.imakita3gyo.tfreemarket.tfreemarket',
  );
}
